# Generated by Django 3.1.1 on 2020-09-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Skypeid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Skype Id')),
                ('Location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location (Country, State, City)')),
                ('created_ts', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_ts', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
