# Generated by Django 3.1.1 on 2020-09-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('Class_Date', models.DateTimeField()),
                ('created_ts', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_ts', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
