# Generated by Django 3.1.1 on 2020-09-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200927_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
