# Generated by Django 3.1.1 on 2020-09-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='students.student'),
        ),
    ]
