# Generated by Django 3.1.1 on 2020-09-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200927_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Class_Date',
            field=models.DateField(),
        ),
    ]
